### ISSUE TITLE
SraAccession column contains Genbank accession for mpox

### ISSUE THREAD

**Issue by theosanderson** [cevo-public/mpox-spectrum-website#11]
I think?

**Comment by chaoran-chen** [comment]
Yes, sorry for that.. I made a mistake at the beginning. I will make some clean ups/fixes next week and probably include additional data.

**Comment by theosanderson** [comment]
Np, just checking was known issue :)

**Comment by chaoran-chen** [comment]
Fixed in cb4b0ea73b3dd89f6f07121db7ad2a126dbf77b2: there is now a new field `accession`.
