### ISSUE TITLE
ENH: Show lineage in overview

### ISSUE THREAD

**Issue by corneliusroemer** [cevo-public/mpox-spectrum-website#16]
Would be great to show lineage here in this table overview.

I've started using mpox genspectrum for the nicer tableview and ability to put it immediately in Nextclade ;)

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/25161793/184359212-a1202af8-98ee-4a78-b3e7-8a3d9d271318.png">

**Comment by chaoran-chen** [comment]
Oh yes, if course!
