### ISSUE TITLE
nit: download filenames

### ISSUE THREAD

**Issue by theosanderson** [cevo-public/mpox-spectrum-website#2]
Maybe this is overly demanding (and definitely not a priority), but a neat feature would be if access to the fasta files could be served from a URL like `https://mpox-lapis.gen-spectrum.org/v1/sample/fasta-aligned.fa` - because then I could run `wget https://mpox-lapis.gen-spectrum.org/v1/sample/fasta-aligned.fa`. 

(I do now see that there are ways for me to add parameters to wget to resolve this myself).

Thanks as ever

**Comment by chaoran-chen** [comment]
Hi Theo! I think that I prefer the endpoint to be just `/fasta-aligned` without any file ending. But as you, I think, found out, `wget -O` should solve it for you.

**Comment by theosanderson** [comment]
Thanks for considering :)
