### ISSUE TITLE
Data hasn't been updated since April 2023

### ISSUE THREAD

**Issue by corneliusroemer** [cevo-public/mpox-spectrum-website#21]
There are new lineages now (C.1, B.1.18-B.1.20) plus more sequences, good reason to update!

<img width="781" alt="image" src="https://github.com/GenSpectrum/mpox-spectrum-website/assets/25161793/216fd96c-7716-4051-96dd-c7a1af88b310">

**Comment by chaoran-chen** [comment]
It's up-to-date again and should again update every day. Please let me know if you notice that it doesn't.
