### ISSUE TITLE
Feature: Allow selection of sequences to export/share with integrations based on sequence table

### ISSUE THREAD

**Issue by corneliusroemer** [cevo-public/mpox-spectrum-website#4]
It could be nice to be able to select sequences from the sequence view, to export to Nextclade/FASTA download etc, similar to traditional databases like GISAID and Genbank:
<img width="2511" alt="image" src="https://user-images.githubusercontent.com/25161793/171186224-dc5da57b-2b2c-4fc1-a306-660a00e2c799.png">

**Comment by anastasia-escher** [comment]
@chaoran-chen could you please post the link to the Material UI table you mentioned?
