### ISSUE TITLE
bug: No date in metadata download for partial dates

### ISSUE THREAD

**Issue by theosanderson** [cevo-public/mpox-spectrum-website#8]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/19732295/171904062-79e6b4cd-ca7d-45bd-b94c-d9a568b1897c.png">

vs. 

<img width="589" alt="image" src="https://user-images.githubusercontent.com/19732295/171904180-6e1e4a76-2ee3-4650-8fdf-bc14a8b76169.png">

**Comment by chaoran-chen** [comment]
This is for some use cases certainly inconvenient but not actually a bug. The thing is that I would like to guarantee that the "date" field contains a proper and complete ISO date or nothing.

See https://mpox-lapis.genspectrum.org/docs/#date-handling

**Comment by chaoran-chen** [comment]
This way, the API remains easy to use for users who are lazy/don't care about partial dates because they can just take the value in "date" and put it into any default date parsers. People who care about partial dates need to use the "year" and "month" fields.

**Comment by theosanderson** [comment]
Apologies - I had not taken in the year and month columns! Thanks for the patient reply and sorry for failure to rtfm :)

**Comment by chaoran-chen** [comment]
Don't worry! Sorry for making changes to the API/introducing new features without communicating them properly.

**Comment by chaoran-chen** [comment]
(We should introduce release notes.)
